---
name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        description: 'Tag name for the release (e.g., 1.0.1)'
        required: false
        default: latest

  workflow_call:
    inputs:
      tag_name:
        type: string
        description: 'Tag name for the release (e.g., 1.0.1)'
        required: false
        default: latest

env:
  repository: ${{ github.repository.toLowerCase() || 'thevickypedia/pyobservability' }}
  repository_name: ${{ github.repository.name.toLowerCase() || 'pyobservability' }}
  repository_description: ${{ github.event.repository.description || 'ðŸ”Ž Observability UI for PyNinja' }}
  # Corrected tag_name logic with fallback and v-prefix removal
  tag_name: ${{ 
    startsWith(inputs.tag_name || github.event.inputs.tag_name || '', 'v') && 
    (inputs.tag_name || github.event.inputs.tag_name || '')[1:] || 
    (inputs.tag_name || github.event.inputs.tag_name || 'latest')
  }}

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Prerequisites
        run: |
          tags="${{ env.repository }}:latest"
          if [ -n "${{ env.tag_name }}" ] && [ "${{ env.tag_name }}" != "latest" ]; then
            tags+=",${{ env.repository }}:${{ env.tag_name }}"
          fi
          echo "Docker image will be published with tags: ${tags}"
          echo "dockertags=${tags}" >> $GITHUB_ENV
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.dockertags }}
          build-args: |
            VERSION=${{ env.tag_name || 'latest' }}

      - name: Update description
        uses: thevickypedia/describe-docker@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          summary: "${{ env.repository_description }}"
          repository: "${{ env.repository_name }}"
          filename: "README.md"
