---
name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        description: 'Tag name for the release (e.g., 1.0.1)'
        required: false
        default: null

  workflow_call:
    inputs:
      tag_name:
        type: string
        description: 'Tag name for the release (e.g., 1.0.1)'
        required: false
        default: null

env:
  repository: ${{ github.repository || 'thevickypedia/PyObservability' }}
  repository_name: ${{ github.repository.name || 'PyObservability' }}
  repository_description: ${{ github.event.repository.description || 'ðŸ”Ž Observability UI for PyNinja' }}
  # workflow_call first, fallback to workflow_dispatch
  tag_name: ${{ inputs.tag_name || github.event.inputs.tag_name }}

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Prerequisites
        run: |
          tags="${{ env.repository }}:${{ env.tag_name }},${{ env.repository }}:latest"
          echo "Docker image will be published with tags: ${tags}"
          echo "dockertags=${tags}" >> $GITHUB_ENV
        shell: bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.dockertags }}
          build-args: |
            VERSION=${{ env.tag_name || 'latest' }}

      - name: Update description
        uses: thevickypedia/describe-docker@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          summary: "${{ env.repository_description }}"
          repository: "${{ env.repository_name }}"
          filename: "README.md"
